// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-zxOil55i4QMLTT3LBmChfmajYoc6_4',
    appId: '1:635749169049:web:8f2791c72a3fbdf36ec508',
    messagingSenderId: '635749169049',
    projectId: 'chat-app-1d1ae',
    authDomain: 'chat-app-1d1ae.firebaseapp.com',
    storageBucket: 'chat-app-1d1ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu9qQt2gKGKfedNWML0aDW416c2chhtnw',
    appId: '1:635749169049:android:0347e633e7f7c4926ec508',
    messagingSenderId: '635749169049',
    projectId: 'chat-app-1d1ae',
    storageBucket: 'chat-app-1d1ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCFIlHLrlNEOprHwN454hKkcBasHNpu8c',
    appId: '1:635749169049:ios:c9dba31e31a2473f6ec508',
    messagingSenderId: '635749169049',
    projectId: 'chat-app-1d1ae',
    storageBucket: 'chat-app-1d1ae.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCFIlHLrlNEOprHwN454hKkcBasHNpu8c',
    appId: '1:635749169049:ios:21a1c2f1d4b6fdfc6ec508',
    messagingSenderId: '635749169049',
    projectId: 'chat-app-1d1ae',
    storageBucket: 'chat-app-1d1ae.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
